spring:
  datasource:
    url:
    username:
    password:
  kafka:
    producer:
      bootstrap-servers: ${KAFKA_PRODUCER_SERVER}
      properties:
        security:
          protocol: SASL_SSL
        sasl:
          mechanism: PLAIN
          jaas:
            config: ${KAFKA_PRODUCER_JAAS_CONFIG}
        client:
          dns:
            lookup: use_all_dns_ips
        session:
          timeout:
            ms: 30000
        acks: all

kafka:
  topic:
    user: code-with-spring.user
jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000
