spring:
  application:
    name: code-with-spring
  profiles:
    active: ${PROFILE}
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/changelog.yaml
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
  output:
    ansi:
      enabled: always
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
jwt:
  secret: SequenciaDeCaracteresParaAssinarToken
  expiration: 86400000

management:
  endpoints:
    web:
      exposure:
        include: [ "*" ]
  endpoint:
    health:
      show-details: always
