global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:

rule_files:

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: [ 'localhost:9090' ]
  - job_name: 'spring-actuator'
    metrics_path: /acuator/prometheus
    scrape_interval: 10s
    static_configs:
      - targets: [ 'localhost:8080' ]